### PR TITLE
Unable to fetch libpq-dev: work around

### PR DESCRIPTION
**Pull request by jgwerner**
Encountered the following error when building image from source:

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/postgresql-9.3/libpq5_9.3.9-0ubuntu0.14.04_amd64.deb  404  Not Found [IP: 91.189.91.14 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/postgresql-9.3/libpq-dev_9.3.9-0ubuntu0.14.04_amd64.deb  404  Not Found [IP: 91.189.91.14 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Added the following to Dockerfile as a work around fix:

```
Install psycopg2
RUN apt-get update
RUN apt-get -y install libssl-dev
RUN apt-get -y install libpq-dev
RUN /usr/local/bin/pip3 install psycopg2
```

### CODE REVIEW

**Comment by jhamrick** [comment]
Thanks! Why is libssl needed, though? If it's a dependency won't it get installed anyways?

**Comment by jgwerner** [comment]
I would think so. Perhaps it's just a matter of the Ubuntu archive having a broken link?

**Comment by jhamrick** [comment]
I guess my question is, just adding the line for `apt-get update` doesn't fix the problem?

**Comment by jgwerner** [comment]
It does! Sorry about that, inadvertently left the libssl-dev install in there by mistake. Re committed to this repo and systemuser repo.

**Comment by jhamrick** [comment]
No worries. Thanks for the PRs! :+1:

**Pull request merged**
